# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

export JAVA_HOME=/usr/lib/jvm/java-1.5.0
PATH=$PATH:$HOME/bin:$JAVA_HOME

export PATH
export CLASSPATH=$ORACLE_HOME/jdbc/lib/ojdbc5.jar:/usr/lib/jvm/java-1.5.0/lib:/usr/lib/jvm/java-1.5.0/jre/lib:$CLASSPATH
