/** DO NOT EDIT THIS FILE IN ANY WAY **/

#include <iostream> // for cin and cout

using namespace std;

#ifndef BRAIN_H
/* This file only has one function, which represents the hedgehog's brain.
 * The function accepts a 5x5 matrix that represents what the hedgehog can see.
 * The function outputs an integer, which is the move the hedgehog will make.
 * 
 * The 5x5 matrix is indexed as rows first, columns second.
 * The layout is:
 *         C  C  C  C  C
 *         o  o  o  o  o
 *         l  l  l  l  l
 *         0  1  2  3  4
 *  Row 0 [ ][ ][ ][ ][ ]
 *  Row 1 [ ][ ][ ][ ][ ]
 *  Row 2 [ ][ ][ ][ ][ ]
 *  Row 3 [ ][ ][ ][ ][ ]
 *  Row 4 [ ][ ][^][ ][ ]
 * The ^ at position 4,2 is the hedgehog itself.
 * The values in the matrix will be:
 *  -1 = The hedgehog cannot go here
 *   0 = There is nothing here
 *   1 = There is a seedling here (You can't eat it, it is too small)
 *   2 = A slightly larger seedling (You still can't eat it)
 *   3 = An even larger seedling (Not yet - you can eat it soon)
 *   4 = It is turning into a plant
 *   5 = It has a few leaves
 *   6 = It is getting bigger
 *   7 = It is a full plant now
 *   8 = It is budding
 *   9 = It is starting to bloom
 *  10 = It is full grown now
 * It should be obvious that you want to eat when psotion 3,2 has a value greater than 3.
 * The higher the number, the more health the hedgehog will receive from eating the plant.
 * 
 * It is important to note that the 5x5 matrix is based on the hedgehog's point of view.
 * When the hedgehog turns, the 5x5 matris will change such that the hedgehog is always
 * in position 4,2 and looking forward.
 * 
 * The actions that the hedgehog can make are:
 *   0 = Do nothing, just sit still
 *   1 = Eat - which will give health if position 3,2 has a value greater than 4
 *   2 = Step forward (move into position 3,2)
 *   3 = Turn right, which rotates the hedgehog's point of view
 *   4 = Turn left, which rotates the hedgehog's point of view
 * 
 * Notes:
 * The hedgehog loses 1 health every turn.
 * Plants grow by 1 every turn.
 * If you eat and there is a plant in position 3,2, it will turn to value 1, even if you don't benefit from it.
 * If you eat and there is nothing in 3,2, there is no benefit.
 * If you try to move into a plant that has a value greater than 3, it will block your movement.
 * If you try to move into a -1 location, you will be blocked from moving.
 */
int make_move(int view[5][5]);

#endif
#define BRAIN_H
