/** DO NOT EDIT THIS FILE IN ANY WAY **/

#include <iostream> // for cin and cout
#include <cstdlib> // for rand()
#include <ctime> // for time()
using namespace std;

#ifndef MAIN_H
/* This program is a game in which the player tries to keep a hedgehog alive.
 * Each turn, the player will get to tell the hedgehog to perform one action.
 * The hedgehog gets hungrier with each turn and will starve to death if the
 * user isn't able to get the hedgehog to food.
 */

/* Define is used to replace constant values with words for easier use.
 * Here, we define the world width/height and the hedgehog's starting location.
 * You should be able to make out the purpose of all the other defines.
 */
#define W_WIDTH 20
#define W_HEIGHT 15
#define BUSH_COUNT 15
#define START_X 5
#define START_Y 5
#define MAX_HEALTH 20
#define MAX_TURNS 100

/* Print a welcome message to the player.
 */
void welcome();

/* Show the world.
 * World is the 2x2 world array.
 * hx and hy are the position of the hedgehog.
 * hd is the direction the hedgehog is facing.
 * health is the hedgehog's remaining health.
 */
void show_world(int world[][W_WIDTH], int hx, int hy, int hd, int health);

/* Create a 5x5 matrix of the hedgehog's point of view.
 */
void get_view(int view[][5], int world[][W_WIDTH], int hx, int hy, int hd);

/* Make all the bushes grow by 1 until they reach a max of 10.
 */
void grow(int world[][W_WIDTH]);

#endif
#define MAIN_H
